# Generated by Django 2.1.2 on 2018-11-26 16:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('done', models.BooleanField(default=False)),
                ('done_by', models.ForeignKey(null=True, on_delete='SET_NULL', related_name='+', to=settings.AUTH_USER_MODEL)),
                ('issued_by', models.ForeignKey(on_delete='CASCADE', related_name='issued', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
