# Generated by Django 2.1.2 on 2018-11-28 08:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tdl', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='done_by',
            field=models.ForeignKey(blank=True, null=True, on_delete='SET_NULL', related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
